### ISSUE TITLE
Issue when running DRY_RUN=1

### ISSUE THREAD

**Issue by pacospace** [thoth-station/slo-reporter#139]
**Describe the bug**
SLO reporter cannot run in  DRY_RUN mode

**To Reproduce**
1. Run SLO reporter in DRY RUN

**Expected behavior**
Dry run correctly show example HTML.

**Screenshots**
```
INFO:thoth.slo_reporter.utils:Retrieving... 
pypi_knowledge_graph/pypi_knowledge_graph-2020-10-08.csv
Traceback (most recent call last):
  File "app.py", line 326, in <module>
    main()
  File "app.py", line 321, in main
    day_of_week=day_of_week,
  File "app.py", line 273, in run_slo_reporter
    email_message = generate_email(sli_values_map, configuration=configuration, sli_report=sli_report)
  File "app.py", line 212, in generate_email
    message += "\n" + report_method(metric_data)
  File "/home/fmurdaca/work/aicoe/slo-reporter/thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py", line 118, in _report_sli
    last_week_data = retrieve_thoth_sli_from_ceph(self.configuration.ceph_sli, sli_path, self.total_columns)
  File "/home/fmurdaca/work/aicoe/slo-reporter/thoth/slo_reporter/utils.py", line 120, in retrieve_thoth_sli_from_ceph
    retrieved_data = ceph_sli.retrieve_blob(object_key=ceph_path).decode('utf-8')
AttributeError: 'str' object has no attribute 'retrieve_blob'
```

**Additional context**

**Comment by bissenbay** [comment]
@pacospace I'm getting different error:
```
Traceback (most recent call last):
  File "app.py", line 326, in <module>
    main()
  File "app.py", line 321, in main
    day_of_week=day_of_week,
  File "app.py", line 273, in run_slo_reporter
    email_message = generate_email(sli_values_map, configuration=configuration, sli_report=sli_report)
  File "app.py", line 212, in generate_email
    message += "\n" + report_method(metric_data)
  File "/home/bdauletb/Documents/thoth/slo-reporter/thoth/slo_reporter/sli_python_knowledge_graph/sli_pypi_knowledge_graph.py", line 118, in _report_sli
    last_week_data = retrieve_thoth_sli_from_ceph(self.configuration.ceph_sli, sli_path, self.total_columns)
AttributeError: 'Configuration' object has no attribute 'ceph_sli'
```
Steps to produce the errors above:
1. `git clone slo-reporter`
2. fill out all ENV variables in `.env`, especially put `DRY_RUN=1`
3. `pipenv install`
4. pipenv run python3 app.py`

And this is caused because, we initialize ceph connection in `Configuration` initialization, only if `DRY_RUN-0`, it's here: https://github.com/thoth-station/slo-reporter/blob/master/thoth/slo_reporter/configuration.py#L98.

Suggested solution: Just initialize ceph connection regardless of `DRY_RUN`, WDYT?
How did you get your error?

**Comment by pacospace** [comment]
Sorry I added `self.ceph_sli = "dry_run"` as well in configuration:

```
        if dry_run:
            # Thoth
            self.environment = "dry_run"
            self.backend_namespace = "thoth-dry-run"
            self.middletier_namespace = "thoth-dry-run"
            self.amun_inspection_namespace = "thoth-dry-run"
            self.instance = "dry_run"
            self.instance_wc_backend = "dry_run"
            self.instance_wc_middletier = "dry_run"
            self.instance_wc_amun_inspection = "dry_run"
            self.ceph_sli = "dry_run"
```

to run the dry run correctly `report_method` should have a check if dry run and provide default values just to show how the HTML final template would look like
